### PR TITLE
fix: filter lavalink error

### LINKED ISSUE #171: Everytime Quaver gets disconnected or gets an error from Lavalink, treats it as a crash.
**Describe the bug**
What isn't working as intended, and what does it affect?
https://github.com/ZapSquared/Quaver/blob/21b864d268e172f02bf7bdd4bb9522ced5807e7d/events/music/error.js#L1-L11
Lavalink disconnection and error listeners and how it shuts down.
Affects: User experience, functionality

**Affected versions**
What versions are affected by this bug? (e.g. >=3.0.1, 2.5.1-2.6.3, >=1.2.0)
3.4.0-next.10 and so on.

**Steps to reproduce**
Steps to reproduce the behavior. (e.g. click on a button, enter a value, etc. and see error)
1. Run Quaver
2. Run Lavalink
3. Play a track on Quaver on stage or voice channel
4. While a track is running, stop your Lavalink instance.

**Expected behavior**
What is expected to happen?
Not making Quaver treat Lavalink disconnection or errors as crashes since it's outside Quaver.

**Actual behavior**
What actually happens? Attach or add errors or screenshots here as well.
As Lavalink encounters an error, Quaver has a listener `bot.music.on('error, err`
It will shut down the process with an eventType of nothing.

shuttingDown does not filter that, so treats it as a crash.
https://github.com/ZapSquared/Quaver/blob/21b864d268e172f02bf7bdd4bb9522ced5807e7d/main.js#L120

### PR DESCRIPTION
**Pull request by Xayanide**
### Thank you for your interest in contributing!
Before proceeding, please review the [guidelines for contributing](https://github.com/ZapSquared/Quaver/blob/master/CONTRIBUTING.md).

Fixes #171 

- [x] Are you targeting the `next` branch? (right side)
- [x] Did you review the guidelines for contributing?
- [x] Does your code pass linting checks?
- [ ] Did you document your code?
- [x] Is this change necessary?

### Scope of change
- [ ] Major change
- [x] Minor change
- [ ] Documentation only

### Type of change
- [x] Bug fix
- [ ] Feature
- [ ] Other

### Description
Please describe the changes.

I changed and passed a custom eventType name of `Lavalink Error` instead for to specify that it is a Lavalink error and unrelated to Quaver.

I added `Lavalink Error` eventType in one of the first filters for it to not treat the event as a crash.

I did not add `Lavalink Error` in one of the last filters of the function because it is an error in general anyway, so I let it log the error in error.log.

If there is a better name for the said eventType. Please, suggest.

Also, please check for any more oversights.

### CODE REVIEW

File: events/music/error.js [hunk 1]
```diff
@@ -6,6 +6,6 @@ module.exports = {
 	once: false,
 	execute(err) {
 		logger.error({ message: 'An error occurred. Quaver will now shut down to prevent any further issues.', label: 'Lavalink' });
-		shuttingDown('', err);
+		shuttingDown('Lavalink Error', err);
```
Comment (zapteryx) [inline events/music/error.js:9]: i think it should be `lavalink` instead, don't really need to put any more than that

Comment (zapteryx) [inline events/music/error.js:9]: i think it should be `lavalink` instead, don't really need to put any more than that

**Review by zapteryx — CHANGES_REQUESTED** [review]

**Review by zapteryx — APPROVED** [review]
