### PR TITLE
fix: end stage on disconnection if it exists (Fixes #126)

### LINKED ISSUE #126: Quaver does not end the stage, when Quaver leaves from a Stage channel.
**Describe the bug**
Quaver does not end the stage channel once Quaver leaves.

**Affected versions**
What versions of Quaver are affected by this bug?
All versions after 2.8.0

**To reproduce**
1. Go to a stage channel so Quaver starts the stage.
2. Play any track.
3. Make Quaver leave the stage channel by moving it to voice or another stage channel.
> Music by Quaver is still showing in the first Stage channel.

**Expected behavior**
It should end the stage gracefully without conflicting anything.

### PR DESCRIPTION
**Pull request by Xayanide**
Fixes #126
### Thank you for your interest in contributing!
Before proceeding, please review the [guidelines for contributing](https://github.com/ZapSquared/Quaver/blob/master/CONTRIBUTING.md).

- [x] Are you targeting the `next` branch? (right side)
- [x] Did you review the guidelines for contributing?
- [x] Does your code pass linting checks?
- [x] Did you document your code?
- [ ] Is this change necessary?

### Scope of change
- [ ] Major change
- [x] Minor change
- [ ] Documentation only

### Type of change
- [x] Bug fix
- [ ] Feature
- [ ] Other

### Description
Please describe the changes.

Ends the stage when Quaver gets disconnected from a Stage Channel that has a Stage Instance active.

This is not a full implementation since I excluded one condition. 

## What is the difference between `voiceChannel`  and `oldState`
- `voiceChannel` is for fetching the cache of the guild and channels for the active player and direct interactions only.
e.g. User uses the `/disconnect` command, disconnects Quaver and ends the stage instance if one was present.

- `oldState` channel, should only handle ending stage on disconnections for `voiceStateUpdate` only. (**UPDATE**: Superseded by the first way of implementation.)
e.g. User manually disconnects Quaver, counts as a `voiceStateUpdate`, the stage instance will be deleted if one was present.

## Why there is an optional chaining operator here?
```js
		if (voiceChannel?.type === 'GUILD_STAGE_VOICE') {
```

I think it is highly likely on some `disconnect()` calls absurd or not, the `type` in `voiceChannel` ~~or `oldVoiceChannel`~~ becomes undefined, so, just making sure it doesn't crash just because of that, and instead do nothing, for it is supposed to do nothing at any other conditions.

## Why `await` and `async`?
I think try catch will not be able to work without it.

## Why `try catch`?
In the most absurd conditions, try catch will prevent them from crashing Quaver.

## Why not just `voiceChannel` alone and not include `oldVoiceChannel`?
If Quaver gets *manually* disconnected from the stage channel, not from the `/disconnect` command, Quaver will not be able to end the stage since the handler for that is `voiceStateUpdate`'s `oldState`
**UPDATE**: Superseded by the first way of implementation.

## Why you did it like this?
```js
				const oldVoiceChannel = oldState.channel;
				module.exports.oldVoiceChannel = oldVoiceChannel;
```
Honestly, I haven't thought of a better way where to put those statements, so... Looking forward for a better way on where to put that, maybe on top, or suggest changes.
**UPDATE**: Superseded by the first way of implementation. After the review, first way of implementation was actually better. Don't do this, it is bad.

## What was that one condition you excluded making this an incomplete implementation? Why is it excluded?
The condition is: 
`If Quaver gets moved to another voice/stage channel, delete the previous stage instance made in the previous stage channel if present and its stage topic is the locale string MUSIC_STAGE_TOPIC.`
If Quaver gets moved from voice/stage channel to channel with this same condition from the user multiple times, Discord's ratelimiting will hinder its functionality.

If you wanted this to be included again and have a better alternative implementation, suggest.

## Why the statements are below `bot.music.destroyPlayer`?
Avoiding conflicts with `voiceStateUpdate`.
Deleting a stage instance counts as a `voiceStateUpdate`, for that reason, we destroy the player first *before* deleting the stage instance so that "`voiceStateUpdate` from the stage instance delete" will just halt at `if (!player) return;`, touching nothing else, not wasting any more resources.

## Why there are permission checks before deleting a stage instance?
These are needed to be handled If somehow the user abruptly just disabled the said permissions for Quaver while the following conditions were met. Otherwise, an error of `DiscordAPIError: Missing Permissions or Missing Access` would occur in the console.

## Why not suppressing Quaver again first if unsuppressed, then delete the stage instance?
1. I want to reduce contributors of ratelimits, the more of them the faster Quaver gets ratelimited.
2. It is redundant and a waste of resources to suppress Quaver again since ending a stage takes them all in one go.

## Why only delete stage instances that contains the topic: String of locale `MUSIC_STAGE_TOPIC`
1. I want to reduce contributors of ratelimits, the more of them the faster Quaver gets ratelimited.
2. For to not waste anymore resources deleting stage instances Quaver doesn't even own.

## Why `voiceChannel` do not have any locale calls on permission checks but `oldState` has?
`voiceChannel`'s locale calls are handled by `voiceStateUpdate` already while
`oldState` does not have any so they're specific to that statement. Otherwise, if `voiceChannel` had locale calls, everytime a permission check in `voiceStateUpdate` triggers, two embeds would pop up and prompt for the user.

### Testing: Tested

### CODE REVIEW

**Comment by Xayanide** [comment]
There should be a cleaner way of implementing this same functionality tbh

File: classes/MusicHandler.js [hunk 1]
```diff
@@ -8,12 +8,51 @@ module.exports = class MusicHandler {
 		this.player = player;
 	}
 
-	disconnect() {
+	async disconnect() {
 		const { bot } = require('../main.js');
+		const voiceChannel = bot.guilds.cache.get(this.player.guildId).channels.cache.get(this.player.channelId);
+		const { oldVoiceChannel } = require('../events/voiceStateUpdate.js');
```
Comment (zapteryx) [inline classes/MusicHandler.js:14]: `events/voiceStateUpdate.js` does not export `oldVoiceChannel`

File: classes/MusicHandler.js [hunk 2]
```diff
@@ -8,12 +8,51 @@ module.exports = class MusicHandler {
...
+				try {
+					await voiceChannel.stageInstance.delete();
+				}
+				catch (err) {
+					logger.error({ message: `${err.message}\n${err.stack}`, label: 'Quaver' });
+				}
+			}
+			return;
+		}
+		if (oldVoiceChannel?.type === 'GUILD_STAGE_VOICE') {
```
Comment (zapteryx) [inline classes/MusicHandler.js:37]: `oldVoiceChannel?.type === 'GUILD_STATE_VOICE` would always return false because `oldVoiceChannel` is `undefined`

File: events/voiceStateUpdate.js [hunk 3]
```diff
@@ -92,10 +94,10 @@ module.exports = {
 				if (player.pauseTimeout) {
 					clearTimeout(player.pauseTimeout);
 				}
-				player.pauseTimeout = setTimeout(p => {
+				player.pauseTimeout = setTimeout(async p => {
 					logger.info({ message: `[G ${p.guildId}] Disconnecting (inactivity)`, label: 'Quaver' });
 					p.musicHandler.locale('MUSIC_INACTIVITY');
-					p.musicHandler.disconnect();
+					await p.musicHandler.disconnect();
```
Comment (zapteryx) [inline events/voiceStateUpdate.js:100]: there's no need to make this async. timeouts don't work well with async, you can just revert it back

File: events/voiceStateUpdate.js [hunk 4]
```diff
@@ -134,18 +136,18 @@ module.exports = {
...
 		logger.info({ message: `[G ${player.guildId}] Setting pause timeout`, label: 'Quaver' });
 		if (player.pauseTimeout) {
 			clearTimeout(player.pauseTimeout);
 		}
-		player.pauseTimeout = setTimeout(p => {
+		player.pauseTimeout = setTimeout(async p => {
 			logger.info({ message: `[G ${p.guildId}] Disconnecting (inactivity)`, label: 'Quaver' });
 			p.musicHandler.locale('MUSIC_INACTIVITY');
-			p.musicHandler.disconnect();
+			await p.musicHandler.disconnect();
```
Comment (zapteryx) [inline events/voiceStateUpdate.js:150]: remove async/await

**Review by zapteryx — CHANGES_REQUESTED** [review]

File: classes/MusicHandler.js (hunk 2 above)
Comment (Xayanide) [reply classes/MusicHandler.js]: Reverted to the very first way of implementation.

File: classes/MusicHandler.js [hunk 5]
```diff
@@ -8,12 +8,26 @@ module.exports = class MusicHandler {
...
+		const voiceChannel = bot.guilds.cache.get(this.player.guildId).channels.cache.get(this.player.channelId);
 		clearTimeout(this.player.timeout);
 		clearTimeout(this.player.pauseTimeout);
 		this.player.disconnect();
 		bot.music.destroyPlayer(this.player.guildId);
+		if (voiceChannel?.type === 'GUILD_STAGE_VOICE') {
+			const permissions = bot.guilds.cache.get(this.player.guildId).channels.cache.get(this.player.channelId).permissionsFor(bot.user.id);
+			if (!permissions.has(['VIEW_CHANNEL', 'CONNECT', 'SPEAK'])) return;
+			if (!permissions.has(Permissions.STAGE_MODERATOR)) return;
+			if (voiceChannel.stageInstance?.topic === getLocale(guildData.get(`${this.player.guildId}.locale`) ?? defaultLocale, 'MUSIC_STAGE_TOPIC')) {
```
Comment (zapteryx) [inline classes/MusicHandler.js:22]: guilds can change their locale mid-stage and this check would fail

**Review by zapteryx — CHANGES_REQUESTED** [review]

File: classes/MusicHandler.js (hunk 5 above)
Comment (Xayanide) [reply classes/MusicHandler.js:22]: This check is supposed return false for those cases, then it will not delete the stage instance

Comment (Xayanide) [reply classes/MusicHandler.js:22]: Locales, i will test it.

Comment (zapteryx) [reply classes/MusicHandler.js:22]: 👍🏼

**Review by zapteryx — APPROVED** [review]
